name: "FullStack"
on:
  push:


jobs:
  test-host:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        operating-system: [ubuntu-latest]
        php-images: [ 'openmage/php:7.3.20' ]
        magento-version: [ '2.4.0' ]
        mysql-images: [ 'mysql:8']

    services:
      mysql:
        image: ${{ matrix.mysql-images }}
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      fpm:
        image: ${{ matrix.php-images }}
        ports:
          - 9000:9000
        volumes:
          - ${{ github.workspace }}/:/var/www
      #          - ${{ github.workspace }}/.github/workflows/fpm-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      nginx:
        image: flyingmana/openmage-action-service:nginx
        ports:
          - 8080:80
        volumes:
          - ${{ github.workspace }}/:/var/www
#          - ${{ github.workspace }}/.github/workflows/integration/nginx.conf:/etc/nginx/conf.d/default.conf


    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config -g cache-files-dir)"
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: magento
          key: ${{ runner.OS }}-magento-${{ matrix.magento-version }}
      - name: FS check
        run: |
          mkdir -p ${{ steps.composer-cache.outputs.dir }}
          mkdir -p magento
          cp m2-composer-templates/2.4.0-composer.json magento/composer.json
          cp m2-composer-templates/2.4.0-composer.lock magento/composer.lock
          ls -la

      - name: Cache Composer Downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.magento-version }}-2


      - name: Install Magento
        uses: php-actions/composer@v2
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        with:
          command: install --ignore-platform-reqs --working-dir ./magento

      - name: FS check
        run: |
          ls -la
          ls -la magento
          ls -la /home/runner/.composer/cache/files
      - name: docker logs
        run: |
          docker logs "${{ job.services.nginx.id }}"
          docker logs "${{ job.services.fpm.id }}"
